"""The MCP tool contract, snapshotted so a change to it cannot be accidental (A6).

Fifteen agents read the live deployment through these tools. Renaming one, adding a
required argument or changing an argument's type breaks their recall, so the surface
is committed to `docs/tool-surface.json` and a test compares against it.

Tool descriptions are deliberately excluded. They are prose aimed at the model, and
freezing them would turn every wording improvement into a contract change. Names,
argument shapes and behaviour annotations are the contract.

Regenerate after an intentional change:

    python -m memcp.toolsurface --write
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path
from typing import Any

SNAPSHOT_PATH = Path("docs/tool-surface.json")
GENERATOR = "python -m memcp.toolsurface --write"


async def _collect() -> dict[str, Any]:
    from mcp.server.mcpserver import MCPServer

    from memcp.backend.in_memory import InMemoryBackend
    from memcp.config import Config
    from memcp.tools import register_tools

    # in_memory declares every capability, so every conditionally registered tool
    # is present. A backend with fewer capabilities exposes a subset of this.
    backend = InMemoryBackend()
    server = MCPServer("memcp")
    # model_validate rather than the constructor: the surface must not depend on
    # whatever MEMCP_/MEM0_ variables happen to be set in the caller's environment.
    config = Config.model_validate({"MEMCP_BACKEND": "in_memory"})
    register_tools(server, backend, config)
    tools = await server.list_tools()
    return {
        tool.name: {
            "input_schema": _schema(tool),
            "annotations": _annotations(tool),
        }
        for tool in tools
    }


def _schema(tool: Any) -> Any:
    schema: Any = getattr(tool, "input_schema", None) or getattr(tool, "inputSchema", None)
    if schema is None:
        raise RuntimeError(f"tool {getattr(tool, 'name', '?')} exposes no input schema")
    if hasattr(schema, "model_dump"):
        return schema.model_dump(exclude_none=True)
    return schema


def _annotations(tool: Any) -> Any:
    annotations = getattr(tool, "annotations", None)
    if annotations is None:
        return None
    if hasattr(annotations, "model_dump"):
        return annotations.model_dump(exclude_none=True)
    return annotations


def current_surface() -> dict[str, Any]:
    """The tool surface this build exposes."""
    return asyncio.run(_collect())


def render(surface: dict[str, Any] | None = None) -> str:
    tools = current_surface() if surface is None else surface
    payload = {
        "_comment": f"Generated by `{GENERATOR}`. Frozen contract — see memcp/toolsurface.py.",
        "tool_count": len(tools),
        "tools": tools,
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def load(path: Path = SNAPSHOT_PATH) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))["tools"]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=f"Render or check {SNAPSHOT_PATH}")
    parser.add_argument("--write", action="store_true", help=f"write {SNAPSHOT_PATH} in place")
    parser.add_argument("--path", default=str(SNAPSHOT_PATH))
    args = parser.parse_args(argv)
    text = render(current_surface())
    if args.write:
        path = Path(args.path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
