"""Turning a declaration into a running deployment, and back.

Everything written to disk is written here, from the `Deployment` the stack module
built — so what `memcp plan` printed and what `memcp up` creates cannot disagree.

`up` is idempotent by construction: the files are regenerated from the same
declaration, credentials already on disk are reused rather than re-minted, and
`docker compose up` reconciles rather than recreates. `down` stops what `up` started
and keeps the volumes unless you ask for them to go (C5).
"""

from __future__ import annotations

import os
import shutil
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path

from memcp.deploy import compose as compose_yaml
from memcp.deploy.images import MEM0_SOURCE_PIN, MEM0_SOURCE_REPO, PYTHON_BASE
from memcp.deploy.model import Deployment
from memcp.deploy.secretstore import (
    ENV_FILENAME,
    EnvFile,
    mint,
    resolve_secrets,
    write_gitignore,
)
from memcp.deploy.stacks import (
    DEFAULT_TENANT,
    MEMCP_TOKEN_VAR,
    StackOptions,
    build,
)

COMPOSE_FILENAME = "docker-compose.yml"
DEFAULT_DIR = ".memcp"
DEFAULT_TIMEOUT = 600

GENERATED_HEADER = """\
# Generated by `memcp up` — every line comes from the declaration `memcp plan`
# prints. Edit the command, not this file: the next `up` overwrites it.
#
# Secrets are ${INTERPOLATIONS} resolved from .env in this directory, which is mode
# 0600 and gitignored. No credential is written here.

"""


class DeployError(RuntimeError):
    """A provisioning step failed. The message is the operator-facing explanation."""


@dataclass(frozen=True)
class MemcpSource:
    """Where the memcp image is built from."""

    build_context: str
    dockerfile: str | None
    generated: bool
    describe: str


def _repo_root() -> Path | None:
    """The memcp checkout this package is running from, if it is running from one."""
    candidate = Path(__file__).resolve().parents[2]
    if (candidate / "pyproject.toml").exists() and (candidate / "Dockerfile").exists():
        return candidate
    return None


def resolve_source(spec: str, directory: Path) -> MemcpSource:
    """Decide what image memcp itself runs.

    `auto` prefers the checkout this package was imported from, because a developer
    running `memcp up` from a clone means the code in that clone. Falling back to
    PyPI is what makes `pipx install memcp-server && memcp up` work with no clone at
    all. Either way the base image is digest-pinned (G6).
    """
    from memcp import __version__

    if spec == "pypi" or (spec == "auto" and _repo_root() is None):
        return MemcpSource(
            build_context="./memcp-image",
            dockerfile=None,
            generated=True,
            describe=f"memcp-server=={__version__} from PyPI, on {PYTHON_BASE.repository}"
            f":{PYTHON_BASE.tag}",
        )
    if spec == "auto":
        root = _repo_root()
        if root is None:  # pragma: no cover - guarded by the branch above
            raise DeployError("no memcp checkout found")
        return MemcpSource(
            build_context=os.path.relpath(root, directory),
            dockerfile="Dockerfile",
            generated=False,
            describe=f"built from the checkout at {root}",
        )
    root = Path(spec).resolve()
    if not (root / "Dockerfile").exists():
        raise DeployError(
            f"--memcp-source {spec}: no Dockerfile at {root}. Pass a memcp checkout, "
            "the literal 'pypi', or leave it as 'auto'."
        )
    return MemcpSource(
        build_context=os.path.relpath(root, directory),
        dockerfile="Dockerfile",
        generated=False,
        describe=f"built from the checkout at {root}",
    )


def plan_for(
    backend: str,
    directory: Path,
    *,
    port: int,
    bind: str,
    project: str,
    source_spec: str,
    llm_base_url: str | None = None,
) -> tuple[Deployment, MemcpSource]:
    source = resolve_source(source_spec, directory)
    options = StackOptions(
        build_context=source.build_context,
        build_dockerfile=source.dockerfile,
        port=port,
        bind=bind,
        project=project,
        directory=str(directory),
        generates_dockerfile=source.generated,
        llm_base_url=llm_base_url,
    )
    return build(backend, options), source


# --- file generation -------------------------------------------------------


MEMCP_DOCKERFILE = """\
# Generated by `memcp up`. Base image pinned by digest so this deployment runs the
# same bytes tomorrow (G6). Regenerated on every `up`.
FROM {base}

RUN adduser --disabled-password --gecos "" memcp \\
 && mkdir -p /data \\
 && chown memcp:memcp /data

RUN pip install --no-cache-dir "memcp-server=={version}"

USER memcp
EXPOSE 8080
ENTRYPOINT ["python", "-m", "memcp", "serve"]
"""

INIT_DB = """\
#!/bin/bash
# Creates the database mem0's auth tables live in. Generated by `memcp up`.
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT 'CREATE DATABASE mem0_app'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mem0_app')\\gexec
EOSQL
"""


def materialize(
    deployment: Deployment,
    directory: Path,
    source: MemcpSource,
    env_values: dict[str, str],
) -> None:
    """Write every file the deployment needs. Overwrites generated files only."""
    from memcp import __version__

    directory.mkdir(parents=True, exist_ok=True)
    write_gitignore(directory)

    (directory / COMPOSE_FILENAME).write_text(
        compose_yaml.render(deployment.to_compose(), GENERATED_HEADER), encoding="utf-8"
    )
    EnvFile(directory / ENV_FILENAME).write(env_values)

    if source.generated:
        image_dir = directory / "memcp-image"
        image_dir.mkdir(parents=True, exist_ok=True)
        (image_dir / "Dockerfile").write_text(
            MEMCP_DOCKERFILE.format(
                base=f"{PYTHON_BASE.repository}:{PYTHON_BASE.tag}@{PYTHON_BASE.digest}",
                version=__version__,
            ),
            encoding="utf-8",
        )

    if deployment.backend == "mem0":
        init = directory / "init-db.sh"
        init.write_text(INIT_DB, encoding="utf-8")
        init.chmod(0o755)
        fetch_mem0_source(directory / "mem0-src")


def fetch_mem0_source(target: Path) -> None:
    """Clone the pinned mem0 fork. Public repository, so no credential is involved."""
    if shutil.which("git") is None:
        raise DeployError(
            "git is required to provision the mem0 backend: its server image is built "
            f"from {MEM0_SOURCE_REPO} at {MEM0_SOURCE_PIN}. Install git, or use "
            "--backend sqlite, which needs no clone."
        )
    if not (target / ".git").exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        _run(
            ["git", "clone", "--filter=blob:none", "--no-checkout", MEM0_SOURCE_REPO, str(target)]
        )
    _run(["git", "-C", str(target), "fetch", "--depth", "1", "origin", MEM0_SOURCE_PIN])
    _run(["git", "-C", str(target), "checkout", "--force", MEM0_SOURCE_PIN])


def _run(cmd: list[str]) -> None:
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise DeployError(
            f"{' '.join(cmd[:3])} failed ({result.returncode}):\n{result.stderr.strip()}"
        )


# --- docker compose --------------------------------------------------------


def compose_command(directory: Path, args: list[str]) -> list[str]:
    return ["docker", "compose", "-f", str(directory / COMPOSE_FILENAME), *args]


def require_docker() -> None:
    if shutil.which("docker") is None:
        raise DeployError(
            "docker is not on PATH. `memcp up` provisions containers; install Docker "
            "Engine or Docker Desktop and try again."
        )
    probe = subprocess.run(["docker", "compose", "version"], capture_output=True, text=True)
    if probe.returncode != 0:
        raise DeployError(
            "`docker compose` is not available (Compose v2 is required):\n" + probe.stderr.strip()
        )
    info = subprocess.run(["docker", "info"], capture_output=True, text=True)
    if info.returncode != 0:
        raise DeployError(
            "the Docker daemon is not reachable from this shell:\n"
            + (info.stderr.strip() or info.stdout.strip())
        )


def compose_up(directory: Path, timeout: int, *, quiet: bool = False) -> None:
    """Bring the stack up and block until every service is healthy.

    `--wait` is what makes C1's exit code mean something: compose returns non-zero
    if any service fails its healthcheck inside the window, so a half-started stack
    is a failed command rather than a running one that does not work.
    """
    args = ["up", "-d", "--build", "--wait", "--wait-timeout", str(timeout)]
    if quiet:
        args.append("--quiet-pull")
    result = subprocess.run(compose_command(directory, args))
    if result.returncode != 0:
        raise DeployError(
            f"the stack did not become healthy within {timeout}s. Nothing was torn "
            f"down — inspect it with:\n"
            f"  docker compose -f {directory / COMPOSE_FILENAME} ps\n"
            f"  docker compose -f {directory / COMPOSE_FILENAME} logs --tail=200"
        )


def compose_down(directory: Path, *, volumes: bool) -> None:
    args = ["down", "--remove-orphans"]
    if volumes:
        args.append("-v")
    result = subprocess.run(compose_command(directory, args))
    if result.returncode != 0:
        raise DeployError("`docker compose down` failed; see the output above.")


def compose_ps(directory: Path) -> int:
    return subprocess.run(compose_command(directory, ["ps"])).returncode


# --- token lifecycle -------------------------------------------------------


def read_token(directory: Path) -> str | None:
    return EnvFile(directory / ENV_FILENAME).read().get(MEMCP_TOKEN_VAR)


def rotate_token(directory: Path) -> str:
    """Mint a new memcp token, keeping every other value.

    Without this, every deployment keeps its first credential forever, which is the
    permanent shape SEC-2026-0038 has (G5).
    """
    env_path = directory / ENV_FILENAME
    if not env_path.exists():
        raise DeployError(f"no deployment at {directory}. Run `memcp up` first, or pass --dir.")
    env = EnvFile(env_path)
    values = env.read()
    values[MEMCP_TOKEN_VAR] = mint()
    env.write(values)
    return values[MEMCP_TOKEN_VAR]


# --- client snippet --------------------------------------------------------


def client_snippet(token: str, bind: str, port: int) -> str:
    host = "localhost" if bind in ("127.0.0.1", "0.0.0.0") else bind
    return f"""\
{{
  "mcpServers": {{
    "memcp": {{
      "type": "streamable-http",
      "url": "http://{host}:{port}/mcp",
      "headers": {{
        "Authorization": "Bearer {token}"
      }}
    }}
  }}
}}"""


def prepare(
    backend: str,
    directory: Path,
    *,
    port: int,
    bind: str,
    project: str,
    source_spec: str,
    llm_base_url: str | None = None,
) -> tuple[Deployment, MemcpSource, dict[str, str], list[str]]:
    """Resolve the plan and its secrets without creating anything."""
    deployment, source = plan_for(
        backend,
        directory,
        port=port,
        bind=bind,
        project=project,
        source_spec=source_spec,
        llm_base_url=llm_base_url,
    )
    values, minted = resolve_secrets(deployment, directory)
    return deployment, source, values, minted


def elapsed_since(started: float) -> str:
    seconds = time.monotonic() - started
    minutes, secs = divmod(int(seconds), 60)
    return f"{minutes}m{secs:02d}s" if minutes else f"{secs}s"


__all__ = [
    "COMPOSE_FILENAME",
    "DEFAULT_DIR",
    "DEFAULT_TENANT",
    "DEFAULT_TIMEOUT",
    "DeployError",
    "MemcpSource",
    "client_snippet",
    "compose_down",
    "compose_ps",
    "compose_up",
    "elapsed_since",
    "materialize",
    "plan_for",
    "prepare",
    "read_token",
    "require_docker",
    "resolve_source",
    "rotate_token",
]
